language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.1
matrix:
  fast_finish: true
before_install:
# FIXME: I have no idea how and why six==1.11.0 is being installed
- pip uninstall -y six
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout -c travis.cfg annotate
- bin/buildout -c travis.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage --output-dir=htmlcov -t "--layer=!Robot"
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
